/* Autogenerated with kurento-module-creator */

#ifndef __TRAFFIC-COUNT_IMPL_HPP__
#define __TRAFFIC-COUNT_IMPL_HPP__

#include "OpenCVFilterImpl.hpp"
#include "traffic-count.hpp"
#include <EventHandler.hpp>
#include <boost/property_tree/ptree.hpp>
#include "traffic-countOpenCVImpl.hpp"

namespace kurento
{
namespace module
{
namespace traffic-count
{
class traffic-countImpl;
} /* traffic-count */
} /* module */
} /* kurento */

namespace kurento
{
void Serialize (std::shared_ptr<kurento::module::traffic-count::traffic-countImpl> &object, JsonSerializer &serializer);
} /* kurento */

namespace kurento
{
class MediaPipelineImpl;
} /* kurento */

namespace kurento
{
namespace module
{
namespace traffic-count
{

class traffic-countImpl : public OpenCVFilterImpl, public virtual traffic-count, public virtual traffic-countOpenCVImpl
{

public:

  traffic-countImpl (const boost::property_tree::ptree &config, std::shared_ptr<MediaPipeline> mediaPipeline);

  virtual ~traffic-countImpl () {};

  /* Next methods are automatically implemented by code generator */
  virtual bool connect (const std::string &eventType, std::shared_ptr<EventHandler> handler);
  virtual void invoke (std::shared_ptr<MediaObjectImpl> obj,
                       const std::string &methodName, const Json::Value &params,
                       Json::Value &response);

  virtual void Serialize (JsonSerializer &serializer);

private:

  class StaticConstructor
  {
  public:
    StaticConstructor();
  };

  static StaticConstructor staticConstructor;

};

} /* traffic-count */
} /* module */
} /* kurento */

#endif /*  __TRAFFIC-COUNT_IMPL_HPP__ */
