/* Autogenerated with kurento-module-creator */

#ifndef __TRAFFIC-COUNT_OPENCV_IMPL_HPP__
#define __TRAFFIC-COUNT_OPENCV_IMPL_HPP__

#include <OpenCVProcess.hpp>
#include "traffic-count.hpp"
#include <EventHandler.hpp>

namespace kurento
{
namespace module
{
namespace traffic-count
{

class traffic-countOpenCVImpl : public virtual OpenCVProcess
{

public:

  traffic-countOpenCVImpl ();

  virtual ~traffic-countOpenCVImpl () {};

  virtual void process (cv::Mat &mat);

};

} /* traffic-count */
} /* module */
} /* kurento */

#endif /*  __TRAFFIC-COUNT_OPENCV_IMPL_HPP__ */
