/* Autogenerated with kurento-module-creator */

#include "traffic-countOpenCVImpl.hpp"
#include <KurentoException.hpp>

namespace kurento
{
namespace module
{
namespace traffic-count
{

traffic-countOpenCVImpl::traffic-countOpenCVImpl ()
{
}

/*
 * This function will be called with each new frame. mat variable
 * contains the current frame. You should insert your image processing code
 * here. Any changes in mat, will be sent through the Media Pipeline.
 */
void traffic-countOpenCVImpl::process (cv::Mat &mat)
{
  // FIXME: Implement this
  throw KurentoException (NOT_IMPLEMENTED, "traffic-countOpenCVImpl::process: Not implemented");
}



} /* traffic-count */
} /* module */
} /* kurento */
